# Generated by Django 2.2.4 on 2019-12-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191209_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reg_date',
            field=models.DateField(null=True),
        ),
    ]
