# Generated by Django 2.2.4 on 2019-12-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_reg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
