# Generated by Django 2.2.4 on 2019-12-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='selected',
            field=models.IntegerField(default=1),
        ),
    ]
