# Generated by Django 2.2.4 on 2019-12-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20191219_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
