# Generated by Django 2.2.4 on 2019-12-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_categoria'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table=None,
        ),
    ]
